### ISSUE TITLE
snowpack usage with bootstrap and jquery?

### ISSUE THREAD

**Issue by khoivan88** [stefanfrede/11st-starter-kit#42]
Hi, 

Thank you very much for sharing your project. I am looking into way convert my current 11ty webpage project to using some sort of bundle for speed and page weight optimization. Currently, my pages using Bootstrap CDN as well as jQuery CDN. Since there are a large portion of these libraries that I don't use, I thought perhaps some bundle would help (I have no experience in using any packet bundle before). I did hear about snowpack (good things like speeds and some concerns like it only works with some types of node packages) on learning about package bundler and I found your repo. If you don't mind, I have a couple of questions:

- Do you know if snowpack would be able to slim down and package only what I need for my page from Bootstrap and jQuery? css would be a plus as well?
- I was also looking into parcel vs snowpack and i thought parcel might fit better for my need but as inexperienced as I am, I thought asking for opinion would be best :)!!

Thank you so much!!

**Comment by stefanfrede** [comment]
> Do you know if snowpack would be able to slim down and package only what I need for my page from Bootstrap and jQuery? css would be a plus as well?

You could use `@snowpack/plugin-webpack` instead of `@snowpack/plugin-optimze` which will bundle your build. You are also able to extend the webpack config with which you should be able to purge unused styles from Bootstrap and tree-shake unused code from jQuery.

Read up here https://www.snowpack.dev/#optimized-builds and here https://github.com/snowpackjs/snowpack/tree/master/plugins/plugin-webpack#extending-the-default-webpack-config.

> I was also looking into parcel vs snowpack and i thought parcel might fit better for my need but as inexperienced as I am, I thought asking for opinion would be best :)!!

When I have to bundle my code I prefer webpack. It can be a configuration hell, but I have my own boilerplate which speeds things up for me: https://github.com/stefanfrede/webpack-boilerplate.
